import classes.McColors
import classes.ZenColor
import core.Modpack

Modpack.LOGGER.info("🍼 Creating fluids...")

McColors.colors.each { c ->
    content.createFluid("${c}dyedwater")
        .setColor(ZenColor.getColor(c).rgb())
        .register()
}

content.createFluid('sulfur')
    .setColor(0xFFFFFF)
    .setTemperature(400)
    .setDensity(1800)
    .setViscosity(5000)
    .register()

content.createFluid('oil')
    .setColor(0x000000)
    .setDensity(700)
    .setViscosity(2000)
    .register()

content.createFluid('lila')
    .setColor(0x8000D0)
    .noBlock()
    .register()

// food
content.createFluid('fondue')
    .setColor(0x804000)
    .setTemperature(330)
    .noBlock()
    .register()

content.createFluid('hotwine')
    .setColor(0x804000)
    .setTemperature(330)
    .noBlock()
    .register()

content.createFluid('wine')
    .setColor(0x804000)
    .setTemperature(330)
    .noBlock()
    .register()

// bases
content.createFluid('beefstock')
    .setColor(0x804000)
    .setTemperature(330)
    .noBlock()
    .register()

content.createFluid('boilingwater')
    .setColor(0xFFFFFF)
    .setTemperature(373)
    .noBlock()
    .register()

content.createFluid('bonestock')
    .setColor(0x804000)
    .setTemperature(330)
    .noBlock()
    .register()

content.createFluid('brownmushroomstock')
    .setColor(0xAA9900)
    .setTemperature(330)
    .noBlock()
    .register()

content.createFluid('cheesesoupbase')
    .setColor(0xAA9900)
    .setTemperature(330)
    .noBlock()
    .register()

content.createFluid('clamstock')
    .setColor(0xCCAA00)
    .setTemperature(330)
    .noBlock()
    .register()

content.createFluid('crawfishstock')
    .setColor(0xCCAA00)
    .setTemperature(330)
    .noBlock()
    .register()

content.createFluid('dinosaurstock')
    .setColor(0xCCAA00)
    .setTemperature(330)
    .noBlock()
    .register()

content.createFluid('fishstock')
    .setColor(0xCCAA00)
    .setTemperature(330)
    .noBlock()
    .register()

content.createFluid('frogstock')
    .setColor(0xCCAA00)
    .setTemperature(330)
    .noBlock()
    .register()

content.createFluid('horsestock')
    .setColor(0xCCAA00)
    .setTemperature(330)
    .noBlock()
    .register()

content.createFluid('hotmilk')
    .setColor(0xFFFFFF)
    .setTemperature(373)
    .noBlock()
    .register()

content.createFluid('llamastock')
    .setColor(0xCCAA00)
    .setTemperature(330)
    .noBlock()
    .register()

content.createFluid('lobsterstock')
    .setColor(0xCCAA00)
    .setTemperature(330)
    .noBlock()
    .register()

content.createFluid('porkstock')
    .setColor(0xAA9900)
    .setTemperature(330)
    .noBlock()
    .register()

content.createFluid('poultrystock')
    .setColor(0xCCAA00)
    .setTemperature(330)
    .noBlock()
    .register()

content.createFluid('redmushroomstock')
    .setColor(0xAA9900)
    .setTemperature(330)
    .noBlock()
    .register()

content.createFluid('shrimpstock')
    .setColor(0xCCAA00)
    .setTemperature(330)
    .noBlock()
    .register()

content.createFluid('snailstock')
    .setColor(0xCCAA00)
    .setTemperature(330)
    .noBlock()
    .register()

content.createFluid('vegetablestock')
    .setColor(0xCCAA00)
    .setTemperature(330)
    .noBlock()
    .register()

content.createFluid('vennisonstock')
    .setColor(0xAA9900)
    .setTemperature(330)
    .noBlock()
    .register()

content.createFluid('whitesauce')
    .setColor(0xAA9900)
    .setTemperature(330)
    .noBlock()
    .register()

//soups
content.createFluid('beetrootsoup')
    .setColor(0xAA9900)
    .setTemperature(330)
    .noBlock()
    .register()

content.createFluid('broccolicheesesoup')
    .setColor(0xAA9900)
    .setTemperature(330)
    .noBlock()
    .register()

content.createFluid('carrotandrabbitstew')
    .setColor(0xAA9900)
    .setTemperature(330)
    .noBlock()
    .register()

content.createFluid('carrotmushroomandrabbitstew')
    .setColor(0xAA9900)
    .setTemperature(330)
    .noBlock()
    .register()

content.createFluid('carrotpotatoandrabbitstew')
    .setColor(0xAA9900)
    .setTemperature(330)
    .noBlock()
    .register()

content.createFluid('clamchowder')
    .setColor(0xAA9900)
    .setTemperature(330)
    .noBlock()
    .register()

content.createFluid('cornchowder')
    .setColor(0xAA9900)
    .setTemperature(330)
    .noBlock()
    .register()

content.createFluid('mushroomstew')
    .setColor(0xAA9900)
    .setTemperature(330)
    .noBlock()
    .register()

content.createFluid('mushroomandrabbitstew')
    .setColor(0xAA9900)
    .setTemperature(330)
    .noBlock()
    .register()

content.createFluid('mushroompotatoandrabbitstew')
    .setColor(0xAA9900)
    .setTemperature(330)
    .noBlock()
    .register()

content.createFluid('potatoandrabbitstew')
    .setColor(0xAA9900)
    .setTemperature(330)
    .noBlock()
    .register()

content.createFluid('potatosoup')
    .setColor(0xAA9900)
    .setTemperature(330)
    .noBlock()
    .register()

content.createFluid('rabbitstew')
    .setColor(0xAA9900)
    .setTemperature(330)
    .noBlock()
    .register()

content.createFluid('tomatosoup')
    .setColor(0xAA9900)
    .setTemperature(330)
    .noBlock()
    .register()
